version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t 808865497406.dkr.ecr.us-east-1.amazonaws.com/inventory-management:latest .
      - docker tag 808865497406.dkr.ecr.us-east-1.amazonaws.com/inventory-management:latest 808865497406.dkr.ecr.us-east-1.amazonaws.com/inventory-management:$IMAGE_TAG
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 808865497406.dkr.ecr.us-east-1.amazonaws.com/inventory-management:$IMAGE_TAG
      - echo Writing image definitions file...
      - printf '[{"name":"inventory-app","imageUri":"%s"}]' 808865497406.dkr.ecr.us-east-1.amazonaws.com/inventory-management:$IMAGE_TAG > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
