version: 0.2

env:
  variables:
    AWS_DEFAULT_REGION: "us-east-1" # Must match ECR repository region
    ECR_REPO_URI: "596509374816.dkr.ecr.us-east-1.amazonaws.com/inventory-management"
    IMAGE_TAG: "latest"

phases:
  pre_build:
    commands:
      - echo "Fetching AWS account ID..."
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - ECR_REPO_URI="${AWS_ACCOUNT_ID}.dkr.ecr.${AWS_DEFAULT_REGION}.amazonaws.com/inventory-management"
      - echo "Logging in to ECR: $ECR_REPO_URI"
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $ECR_REPO_URI
  build:
    commands:
      - echo "Building application..."
      - mvn clean package
      - docker build -t $ECR_REPO_URI:latest .
      - docker tag $ECR_REPO_URI:latest $ECR_REPO_URI:$IMAGE_TAG
  post_build:
    commands:
      - docker push $ECR_REPO_URI:$IMAGE_TAG
      - printf '[{"name":"inventory-app","imageUri":"%s"}]' $ECR_REPO_URI:$IMAGE_TAG > imagedefinitions.json

artifacts:
  files: imagedefinitions.json
