version: 0.2

env:
  variables:
    ECR_REPO_NAME: "inventory-management"

phases:
  pre_build:
    commands:
      - AWS_ACCOUNT_ID=$(aws sts get-caller-identity --query 'Account' --output text)
      - ECR_REPO_URI="$AWS_ACCOUNT_ID.dkr.ecr.us-east-2.amazonaws.com/$ECR_REPO_NAME"
      - aws ecr get-login-password --region us-east-2 | docker login --username AWS --password-stdin  551899295811.dkr.ecr.us-east-2.amazonaws.com/inventory-management
  build:
    commands:
      - mvn clean package
      - docker build -t 551899295811.dkr.ecr.us-east-2.amazonaws.com/inventory-management:latest .
      - docker tag 551899295811.dkr.ecr.us-east-2.amazonaws.com/inventory-management:latest 551899295811.dkr.ecr.us-east-2.amazonaws.com/inventory-management:latest
  post_build:
    commands:
      - docker push 551899295811.dkr.ecr.us-east-2.amazonaws.com/inventory-management:latest
      - printf '[{"name":"inventory-app","imageUri":"%s"}]' 551899295811.dkr.ecr.us-east-2.amazonaws.com/inventory-management:latest> imagedefinitions.json
artifacts:
  files: imagedefinitions.json
