version: 0.2
phases:
  pre_build:
    commands:
      - echo Logging in to Amazon ECR...
      - aws ecr get-login-password --region $AWS_DEFAULT_REGION | docker login --username AWS --password-stdin $AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com
  build:
    commands:
      - echo Building Docker image...
      - docker build -t 343501691580.dkr.ecr.us-east-1.amazonaws.com/inventory-management:latest .
      - docker tag 343501691580.dkr.ecr.us-east-1.amazonaws.com/inventory-management:latest343501691580.dkr.ecr.us-east-1.amazonaws.com/inventory-management:latest
  post_build:
    commands:
      - echo Pushing Docker image to ECR...
      - docker push 343501691580.dkr.ecr.us-east-1.amazonaws.com/inventory-management:latest
      - echo Writing image definitions file...
      - printf '[{"name":"inventory-app","imageUri":"%s"}]' 343501691580.dkr.ecr.us-east-1.amazonaws.com/inventory-management:latest  > imagedefinitions.json
artifacts:
  files: imagedefinitions.json
# arn:aws:codeconnections:us-east-1:808865497406:connection/c886f3d3-aff9-44d8-83e7-790c91d489e4

# ECR : 343501691580.dkr.ecr.us-east-1.amazonaws.com/inventory-management

# arn:aws:codeconnections:us-east-1:343501691580:connection/fa1a561b-760a-412c-8492-de66ad98ca9f
